spring:
  application:
    name: SpringRestService
  datasource:
    url: jdbc:postgresql://localhost:5432/book_pasal
    username: postgres
    password: Deerwalk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: MySuperSecureJwtSecretKeyThatIsAtLeast32CharsLong!!

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.dwit.developers.springrestservice.mapper

